#! /bin/bash 

PKG_name="test"

declare -A PKG_distro_include

PKG_distro_include["Debian"]="yes"
PKG_distro_include["Arch"]="yes"
PKG_distro_include["RedHat"]="yes"
PKG_distro_include["openSUSE"]="yes"

declare -a PKG_dependencies

PKG_dependencies=(test 

PKG_distro_package_name["Debian","test"]="saddas"
PKG_distro_package_name["Arch","test"]="saddas"
PKG_distro_package_name["RedHat","test"]="saddas"
PKG_distro_package_name["openSUSE","test"]="saddas"


