#! /bin/bash

MAIN_DIR=$(cd ../ && pwd)
source $MAIN_DIR/.env

if [[ -d "$INSTALL_DIR" ]]; then
    echo "*error* There already exists a directory \"$INSTALL_DIR\"."
    exit 1
else
    echo "Copying the files from \"$MAIN_DIR\" to \"$INSTALL_DIR\"..."
    sudo cp -r $MAIN_DIR $INSTALL_DIR

    echo "Concluding the installation..."
    printf "if [[ -f $INSTALL_DIR ]]; then \nsource $INSTALL_DIR \nfi\n" >> $HOME/.bashrc
fi

