#! /bin/bash

MAIN_DIR=$(cd ../ && pwd)
source $MAIN_DIR/.env

if [[ -d "$PKG_INSTALL" ]]; then
    echo "*error* There already exists a directory \"$PKG_INSTALL\"."
    exit 1
else
    echo "Copying the files from \"$MAIN_DIR\" to \"$PKG_INSTALL\"..."
    sudo cp -r $MAIN_DIR $PKG_INSTALL

    echo "Concluding the installation..."
    printf "if [[ -f $PKG_INSTALL ]]; then \nsource $PKG_INSTALL \nfi\n" >> $HOME/.bashrc
fi

