#! /bin/bash
    
# UNINSTALL SCRIPT
    echo "Welcome to the uninstall of the package \"pkg.sh\"."

    if [[ ! -d $PKG_install_dir ]]; then
        echo "The application \"pkg.sh" is not installed."
    else
        while :
        do
            echo "Are you sure to remove \"pkg.sh"?"
            read -e -p "> " remove_package
            if [[ "$remove_package" == "y" ]] || [[ "$remove_package" == "yes" ]] ||
               [[ "$remove_package" == "Y" ]] || [[ "$remove_package" == "YES" ]]; then
             
                echo "Uninstalling \"pkg.sh\"..."
                rm -r $PKG_install_dir
                echo -e -n "Optionally, go to your \"~/.bashrc\" file and delete the following lines:\n---\nif [[ -f $PKG_install_dir/pkg.sh ]]; then \n    source $install_dir/$PKG_name.sh \nfi\n---\n"
                echo "Uninstalling has been finished."
                break
            elif [[ "$remove_package" == "n" ]] || [[ "$remove_package" == "no" ]] ||
                 [[ "$remove_package" == "N" ]] || [[ "$remove_package" == "NO" ]]; then
                echo "Aborting..."
                break
            fi
        echo "Please, write \"y/yes\" or \"n/no\"."
        continue
    fi
