#! /bin/bash

# MAIN FUNCTION
function PKG_name(){
## Includes
source ${BASH_SOURCE%/*}/pkgfile
source ${BASH_SOURCE%/*}/.env
## without options enter in the interactive mode or print help
    if  [[ -z "$1" ]]; then
        if [[ -f "$INSTALL_DIR/config/src/interactive" ]] &&
           [[ -s "$INSTALL_DIR/config/src/interactive" ]]; then
            sh $INSTALL_DIR/config/src/interactive
        else
            cat $INSTALL_DIR/config/src/help.txt
        fi
## "-c", -"cfg" and "--config" options to enter in the configuration mode
    elif ([[ "$1" == "-c" ]] || 
          [[ "$1" == "-cfg" ]] || 
          [[ "$1" == "--config" ]]) &&
          [[ -z "$2" ]]; then
          if [[ -f "$INSTALL_DIR/config/config" ]] &&
           [[ -s "$INSTALL_DIR/config/config" ]]; then
            sh $INSTALL_DIR/config/config
        else
            echo "None configuration mode defined for the \"PKG_name\" function."
        fi
## "-h" and "--help" options to print help
    elif ([[ "$1" == "-h" ]] || 
          [[ "$1" == "--help" ]]) &&
          [[ -z "$2" ]]; then
          cat $INSTALL_DIR/config/help.txt
## "-u" and "--uninstall" options to execute the uninstall script
    elif [[ "$1" == "-u" ]] || [[ "$1" == "--uninstall" ]]; then
        cd $INSTALL_DIR/install
        sh uninstall
        cd - > /dev/null
## (your additional code ...)
    else 
        echo "Option not defined for the \"PKG_name()\" function."
    fi
}
   
