#! /bin/bash

# including the pkgfile
    pkgfile_dir=$(cd ../ && pwd)
    source $pkgfile_dir/pkgfile

# auxiliary function: checking for dependencies
    function PKG_dependencies_check(){
    declare -A PKG_missing_dependencies 
    for dependency in ${PKG_dependencies[@]}; do
        echo "Checking for \"$dependency\"..."
        if [[ -x "$(command -v $dependency)" ]]; then
            echo -e -n "* Ok...\n"
        else
            echo -e -n "Dependency \"$dependency\" is missing...\n"
            PKG_missing_dependencies[$dependency]="$dependency"
        fi
    done
   }
# auxiliary function: installing dependencies
    function PKG_installing_dependencies(){
        if [[ -z ${PKG_missing_dependencies[@]} ]]; then
            echo "All dependencies are already installed..."
        else 
            echo "Installing missing dependencies..."
            for dependency in ${PKG_missing_dependencies[@]}; do
                echo "* Installing dependency \"$dependency\"...\n"
                if [[ ! "${PKG_distro_package_name[$PKG_distro_name,$dependency]}" == "" ]]; then
                    command ${PKG_distros_install_commands[$PKG_distro_name]} ${PKG_distro_package_name[$PKG_distro_name,$dependency]}
                    if [[ -x "$(command -v ${PKG_distro_package_name[$PKG_distro_name,$dependency]})" ]]; then
                        echo "Dependency \"$dependency\" has been installed..."
                    else
                        echo "Found an error. Dependency \"$dependency\" has NOT been installed..."
                    fi
                else
                    command ${PKG_distros_install_commands[$PKG_distro_name]} $dependency
                    if [[ -x "$(command -v $dependency)" ]]; then
                        echo "Dependency \"$dependency\" has been installed..."
                    else
                        echo "Found an error. Dependency \"$dependency\" has NOT been installed..."
                    fi
s                fi
            done
        fi 
    }
# auxiliary function: installing the package
    function PKG_installing_package(){
        PKG_starting_dir=$(cd ../ && pwd)
        echo "Copying the files from \"$PKG_starting_dir\" to \"$install_dir\"..."
        sudo cp -r $PKG_starting_dir $install_dir
    
        echo "Configuring the structural files..."
        structural_files=$(find $install_dir -type f)
        for f in ${structural_files[@]}; do
            sed -i '3i install_dir=$install_dir' $f
        done

        echo "Concluding the installation..."
        printf "if [[ -f $install_dir/$PKG_name.sh ]]; then \nsource $install_dir/$PKG_name.sh \nfi\n" >> $HOME/.bashrc
    }

# INSTALLATION SCRIPT
    echo "Welcome to the installation of the package \"$PKG_name\"."
    if [[ -z "$install_dir" ]]; then
        echo "Installation directory not defined. Please, execute \"./configure\" first."
    else
## identifying the Linux distribution
        echo "Identifying current Linux distribution..."
        distro_name=$(source /etc/os-release && echo $NAME)
        echo "\"$distro_name\" was identified as the current Linux distribution."
## checking if it is in the pkgfile
        for distro in ${PKG_distros[@]}; do
            PKG_distro_name_ckeck="$(grep -R "$distro" /etc/os-release)"
            if [[ "${PKG_distro_include[$distro]}" == "yes" ]] ||
               [[ "${PKG_distro_include[$distro]}" == "Y" ]] ||
               [[ "${PKG_distro_include[$distro]}" == "YES" ]] ||
               [[ "${PKG_distro_include[$distro]}" == "Y" ]] ||
               [[ "${PKG_distro_include[$distro]}" == "Y" ]] ||
               [[ "${PKG_distro_include[$distro]}" == "" ]] &&
               [[ -n $PKG_distro_name_check ]]; then
                PKG_distro_name="$distro"
            else 
                PKG_distro_name=""
            fi
        done

        if [[ -z $PKG_distro_name ]]; then
            echo -e -n "Unfortunately, \"$distro_name\" is not configured in the pkgfile. Thus: \n* If missing, the dependencies must be installed manually.\n"
## checking for dependencies
            echo "Checking for dependencies..."
            PKG_dependencies_check
            echo -e -n "The following dependences are missing and must be installed manually before the installation of \"$PKG_name\":\n"
            for dependency in ${PKG_missing_dependencies[@]}; do
                echo -e -n "\n* $dependency"
            done
        else
            echo "\"$distro_name\" identified in the pkgfile..."
## installing dependencies
            PKG_installing_dependencies
## installing the package
            PKG_installing_package
            printf "\nThe installation of the package \"$PKG_name\"  was finished:\n* Try \"$PKG_name --help\" to get more information on its usage.\n* To uninstall use \"$PKG_name --uninstall\".\n"
        fi
    fi

